CSDTs/CSnap

- cloud.js
- gui.js
- lib/jszip-utils.js
- module-loader.js
I also ended up adding in a library; this is just a start though, much more to do.
> Changed the module loader to conform to intended behavior

- module-loader.js
Really small change, but let me know if you see any issues...
> Modified to work with libraries

- module-loader.js
- objects.js
We probably shoulda done this when talking with Brenda and Poor Ben.
> Fix meta.json reference

- Charles_Changes_To_IDE_Morph.js
- agpl.txt
- gui.js
Check changes made to files for using zip files while offline. gui.js was changed to check if system is online. Zip import has been altered in the last portion of Charles code.
> Changes to Charles IDE_Morph and gui.js

- gui.js
- objects.js
- store.js
Merge and put on dev site when time permits.
> Small changes, mostly for 3D.... 

- gui.js
Do not merge until going public.
> Turn Off 3D Access

- objects.js
Also contains stubs for other things that don't do anything.
> Fix for the white box over background

- gui.js
I think Eglash wanted even more speed, so I pulled down the frame rate of the corral bar to 15fps, and set it to update only when the text changes... no point in constantly redrawing. This will require some module level changes. Grr.
> CPU Usage Improvements

- gui.js
- objects.js
- threads.js
Eglash kindly noted that if you run the Anishinaabe Arcs program ~100 times, it crashes thanks to fun fun memory leaks. This is a fix for that.
> 3D Memory Leak Fix

- gui.js
- morphic.js
- objects.js
used this.penSize() to control tube radius.
> Pen Size Controls 3D Arc Size

- store.js
I didn't think about the fact that the attribute is a string and not a boolean...
> Fix for saving costumes

- objects.js
Fix whitespace issue and
Update SpriteMorph..prototype.getBorderShade function to reflect correct
math. (line 3034)
> Update Pull Request #68

- cloud.js
- gui.js
- objects.js
- widgets.js
The login should work now... apparently someone configured the request wrong.
The getProjectsList command should now request log in if not logged in.
> Fixing some of the login from CSnap problems

- gui.js
- objects.js
- store.js
Allowing new 3D costumes, fixing loading, and changing rotation.
> 3D updates

- cloud.js
Required for put requests. DOH!
> Append Slash

- objects.js
- store.js
Re-hide on draw new
Set invisible on load costumes & objects
Assign visibility on load value or costume
> Hide Sprites On Load

- objects.js
If you drag in a costume, change the color, edit it, and then change
color again, the original pixels will be all messed up. This just
reassigns those original pixels after editing.
> Added a small fix for editing

- gui.js
- module-loader.js
- objects.js
Changes the get application routine, implements a close on focus change for the cancel dialog, and deletes duplicate blocks.
> Req. For Application Location Shift + Fixes

- blocks.js
adding the asset path
fixes #34 without deletion.
> Fix click sound broken

- gui.js
> Added asset path to set language to be able to switch languages

- cloud.js
- gui.js
> Added in save as new project if unique name or published project

- lang-es.js
Adding Spanish translations for all our new primitive blocks, and all our new features.
> Fixing spanish translations

- lang-es.js
Added the shade translation I missed before.
> Update The Spanish Translations

- blocks.js
- byob.js
- gui.js
- lang-es.js
- morphic.js
- objects.js
> Fix exports

- cloud.js
- gui.js
Defaults to Cloud saves, Browser option not added into Save As menu, and a bit of error handling when users enter their login information incorrectly.
> chore: update save as to default to cloud

- Charles_Changes_To_IDE_Morph.js
- blocks.js
- csnap.html
- gui.js
- morphic.js
- objects.js
- parser copy.js
- store.js
- threads.js
Branch for expanded rhythm wheel scripting interface, which allows for the instantiation of custom-named rhythm wheel, audio data structures by users, allows users to build the rhythm wheel by dragging and dropping sounds, and by importing .rw files users might have made in the GUI based rhythm wheel interface.
> Expand rhythm wheels scripting interface
